# fly.toml app configuration file generated for beta-plug-masterda on 2024-12-19T20:30:24-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'beta-plug-masterda'
primary_region = 'qro'

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true # Boolean values don't need quotes
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  app = "npm run dev:all" # This runs your custom script

[resources] # Correct section for resources
  memory = "1024" # Use megabytes for memory
  cpu = "shared"
  cpus = 1